Feature restaurant-page
IjayAbby/restaurant-page pull request #1
Opened 2021-04-30 06:18 UTC by IjayAbby

This is a  restaurant page built with Vanilla JS with implementation of webpck configuration and styling of the same.

2021-04-30 07:40 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @IjayAbby, congratulations on this project :+1: The entry point has been set up nicely :smile: The contents of each tab are stored in a module :100: Each module exports a function that creates a `div` elements, adds the appropriate content and styling :100: 
Let us address the comments below so we can get our project approved:

- Kindly add `webpack-dev-server` to the devDependencies, because we cannot use the `serve` command without installing the webpack-dev-server as in the screenshot below:
![code2](https://user-images.githubusercontent.com/46388113/116662034-c9b82d80-a984-11eb-99a8-044fc15b9809.png)
- Kindly use the recommended `.eslintrc.json` file, do not make any changes. You can find the recommended file [here](https://github.com/microverseinc/linters-config/blob/master/javascript/.eslintrc.json)
- Kindly use the ES6 arrow function instead of the `function` keyword. Kindly check this for all functions
- Kindly fix the broken images on the Menu page

Once these are resolved, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-04-30 07:40 UTC, addod19 commented on src/contact.js
> +function createContact() {
Kindly use the ES6 arrow function instead :muscle:

2021-04-30 07:40 UTC, addod19 commented on src/contact.js
> +function loadContact() {
Kindly use the ES6 arrow function instead

2021-04-30 07:40 UTC, addod19 commented on src/home.js
> +function createHome() {
Kindly use the ES6 arrow function instead

2021-04-30 07:40 UTC, addod19 commented on src/home.js
> +function loadHome() {
Kindly use the ES6 arrow function instead

2021-04-30 07:40 UTC, addod19 commented on src/menu.js
> +function createMenu() {
Kindy use the ES6 arrow function instead

2021-04-30 07:40 UTC, addod19 commented on src/menu.js
> +function createMenuItem(name, description) {
Kindly use the ES6 arrow function instead

2021-04-30 07:40 UTC, addod19 commented on src/menu.js
> +function loadMenu() {
Kindly use the ES6 arrow function instead

2021-04-30 07:40 UTC, addod19 commented on src/website.js
> +function createHeader() {
Kindly use the ES6 arrow function instead

2021-05-02 10:04 UTC, afanimartin approved these changes
## Approved 👏🏿 
Nice work making the requested changes. Merge and proceed to the next project. Good luck!

2021-05-03 07:23 UTC, merged